/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 2dbbed5c96990447ec3e12061d81530e)
declare namespace Cloudflare {
  interface Env {
    SERVER_ADDRESS: "0xFa75d8F07BA244c29cbdb32fD3093D759857072E";
    MCP_ADDRESS: string;
    CLIENT_TEST_PK: string;
    MCP_OBJECT: DurableObjectNamespace<import("./src/index").PayMCP>;
    PAY_AGENT: DurableObjectNamespace<import("./src/index").PayAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "SERVER_ADDRESS" | "MCP_ADDRESS" | "CLIENT_TEST_PK">
    > {}
}
