/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 69a7d4f2982441c7c9e94ba4b4f403f8)
declare namespace Cloudflare {
  interface Env {
    SERVER_ADDRESS: string;
    CLIENT_TEST_PK: string;
    PAY_AGENT: DurableObjectNamespace /* PayAgent */;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "SERVER_ADDRESS" | "CLIENT_TEST_PK">
    > {}
}
