/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: ebf6050f31a817d52d347ae1733648da)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Codemode";
  }
  interface Env {
    Codemode: DurableObjectNamespace /* Codemode */;
    LOADER: WorkerLoader;
    globalOutbound: Service<typeof import("./src/server").globalOutbound>;
    CodeModeProxy: Service<typeof import("./src/server").CodeModeProxy>;
  }
}
interface Env extends Cloudflare.Env {}
